# Project HR

Predict attrition of your valuable employees

[IBM HR Analytics Employee Attrition & Performance](https://www.kaggle.com/pavansubhasht/ibm-hr-analytics-attrition-dataset)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_curve, auc, confusion_matrix

In [5]:
try:
  df = pd.read_csv("data/WA_Fn-UseC_-HR-Employee-Attrition.csv")
except:
  url = "https://raw.githubusercontent.com/anthonyng2/intro_ml_finance/master/data/WA_Fn-UseC_-HR-Employee-Attrition.csv"
  df = pd.read_csv(url)
df.head()

Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0
3   33        No  ...                       3                     0
4   27        No  ...                       2                     2

[5 rows x 35 columns]

In [6]:
from IPython.display import HTML
pd.set_option('display.max_colwidth', -1)
display(HTML(df.head().to_html()))
pd.reset_option('display.max_colwidth')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [8]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [9]:
features = ['Age', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager']

In [10]:
X = df[features]
y = df.Attrition

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, 
                                                    stratify=y)

In [12]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder

In [13]:
num = ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount', 'EmployeeNumber', 
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction',             
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager']

cat = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 
       'MaritalStatus', 'Over18', 'OverTime']

In [14]:
le_bt = preprocessing.LabelEncoder()
le_dept = preprocessing.LabelEncoder()
le_edu = preprocessing.LabelEncoder()
le_gender = preprocessing.LabelEncoder()
le_job = preprocessing.LabelEncoder()
le_marri = preprocessing.LabelEncoder()
le_over18 = preprocessing.LabelEncoder()
le_ot = preprocessing.LabelEncoder()

enc_bt = OneHotEncoder(sparse=False)
enc_dept = OneHotEncoder(sparse=False)
enc_edu = OneHotEncoder(sparse=False)
enc_gender = OneHotEncoder(sparse=False)
enc_job = OneHotEncoder(sparse=False)
enc_marri = OneHotEncoder(sparse=False)
enc_over18 = OneHotEncoder(sparse=False)
enc_ot = OneHotEncoder(sparse=False)

bt = le_bt.fit_transform(X_train.BusinessTravel)
dept = le_dept.fit_transform(X_train.Department)
edu = le_edu.fit_transform(X_train.EducationField)
gender = le_gender.fit_transform(X_train.Gender)
job = le_job.fit_transform(X_train.JobRole)
marri = le_marri.fit_transform(X_train.MaritalStatus)
over18 = le_over18.fit_transform(X_train.Over18)
ot = le_ot.fit_transform(X_train.OverTime)

bt = enc_bt.fit_transform(bt.reshape(-1,1))
dept = enc_dept.fit_transform(dept.reshape(-1,1))
edu = enc_edu.fit_transform(edu.reshape(-1,1))
gender = enc_gender.fit_transform(gender.reshape(-1,1))
job = enc_job.fit_transform(job.reshape(-1,1))
marri = enc_marri.fit_transform(marri.reshape(-1,1))
over18 = enc_over18.fit_transform(over18.reshape(-1,1))
ot = enc_ot.fit_transform(ot.reshape(-1,1))

In [15]:
X_train = pd.concat([X_train[num],
                     pd.DataFrame(np.hstack((bt, dept, edu, gender,
                                             job, marri, over18, ot)))], axis=1)

In [16]:
X_train.shape

(1333, 55)

In [17]:
comb = pd.concat([X_train, y_train], axis=1)
comb = comb.dropna()
comb.shape

(725, 56)

In [18]:
y_train = comb['Attrition']

In [19]:
X_train = comb[X_train.columns]

In [20]:
test_bt = le_bt.transform(X_test.BusinessTravel)
test_dept = le_dept.transform(X_test.Department)
test_edu = le_edu.transform(X_test.EducationField)
test_gender = le_gender.transform(X_test.Gender)
test_job = le_job.transform(X_test.JobRole)
test_marri = le_marri.transform(X_test.MaritalStatus)
test_over18 = le_over18.transform(X_test.Over18)
test_ot = le_ot.transform(X_test.OverTime)

test_bt = enc_bt.fit_transform(test_bt.reshape(-1,1))
test_dept = enc_dept.fit_transform(test_dept.reshape(-1,1))
test_edu = enc_edu.fit_transform(test_edu.reshape(-1,1))
test_gender = enc_gender.fit_transform(test_gender.reshape(-1,1))
test_job = enc_job.fit_transform(test_job.reshape(-1,1))
test_marri = enc_marri.fit_transform(test_marri.reshape(-1,1))
test_over18 = enc_over18.fit_transform(test_over18.reshape(-1,1))
test_ot = enc_ot.fit_transform(test_ot.reshape(-1,1))

In [21]:
X_test = pd.concat([X_test[num],
                     pd.DataFrame(np.hstack((bt, dept, edu, gender,
                                             job, marri, over18, ot)))], axis=1)

In [22]:
X_test.shape

(1166, 55)

In [23]:
test_comb = pd.concat([X_test, y_test], axis=1)
test_comb = test_comb.dropna()
test_comb.shape

(304, 56)

In [24]:
y_test = test_comb['Attrition']
X_test = test_comb[X_test.columns]

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Model 1:

In [26]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[610 112]
 [  2   1]]
0.8427586206896551
[[245  58]
 [  0   1]]
0.8092105263157895


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# Model 2:

In [27]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[611  25]
 [  1  88]]
0.9641379310344828
[[238  50]
 [  7   9]]
0.8125


# Model 3:

In [28]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[612   0]
 [  0 113]]
1.0
[[200  40]
 [ 45  19]]
0.7203947368421053


# Model 4:

In [29]:
clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[612   0]
 [  0 113]]
1.0
[[240  55]
 [  5   4]]
0.8026315789473685


***