# Credit Card Fraud


[Source](https://www.kaggle.com/mlg-ulb/creditcardfraud)

In [1]:
import pandas as pd, numpy as np
import datetime

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_curve, auc, confusion_matrix
from sklearn.model_selection import GridSearchCV

import sklearn
#from sklearn_pandas import DataFrameMapper

import matplotlib.pyplot as plt
from IPython.display import HTML

Unbalanced data issue

In [2]:
try:
  df = pd.read_excel("data/creditcard.xlsx")
except:
  url = "https://github.com/anthonyng2/intro_ml_finance/blob/master/data/creditcard.xlsx?raw=true"
  df = pd.read_excel(url)

df.head()

Time        V1        V2        V3  ...       V28  Amount  Class       fil
0    16  0.694885 -1.361819  1.029221  ...  0.063499  231.71      0  0.917284
1    25  1.114009  0.085546  0.493702  ...  0.004453    4.45      0  0.980440
2    26 -0.535388  0.865268  1.351076  ...  0.025427    1.77      0  0.958214
3    27 -1.452187  1.765124  0.611669  ...  0.120557    1.80      0  0.968873
4    34 -0.291540  0.445575  1.249752  ...  0.062896   18.95      0  0.917209

[5 rows x 32 columns]

In [3]:
df.head()

Time        V1        V2        V3  ...       V28  Amount  Class       fil
0    16  0.694885 -1.361819  1.029221  ...  0.063499  231.71      0  0.917284
1    25  1.114009  0.085546  0.493702  ...  0.004453    4.45      0  0.980440
2    26 -0.535388  0.865268  1.351076  ...  0.025427    1.77      0  0.958214
3    27 -1.452187  1.765124  0.611669  ...  0.120557    1.80      0  0.968873
4    34 -0.291540  0.445575  1.249752  ...  0.062896   18.95      0  0.917209

[5 rows x 32 columns]

In [4]:
pd.set_option('display.max_colwidth', -1)
display(HTML(df.head().to_html()))
pd.reset_option('display.max_colwidth')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


In [5]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class', 'fil'],
      dtype='object')

In [6]:
features = ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
            'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
            'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']

In [7]:
df['Class'].value_counts()

0    28442
1      492
Name: Class, dtype: int64

In [8]:
X = df[features]
y = df['Class']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, 
                                                    stratify=y)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Model 1:

In [11]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[19896    67]
 [   13   277]]
0.9960499679059892
[[8530   30]
 [   3  118]]
0.9961985946319548


# Model 2:

In [12]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[19908    20]
 [    1   324]]
0.9989631165753222
[[8521   26]
 [  12  122]]
0.9956226241216449


# Model 3:

In [13]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[19909     0]
 [    0   344]]
1.0
[[8508   23]
 [  25  125]]
0.9944706831010253


# Model 4:

In [14]:
clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(confusion_matrix(clf.predict(X_train), y_train))
print(accuracy_score(clf.predict(X_train), y_train))
print(confusion_matrix(clf.predict(X_test), y_test))
print(accuracy_score(clf.predict(X_test), y_test))

[[19909     0]
 [    0   344]]
1.0
[[8531   23]
 [   2  125]]
0.9971201474484507


***